export const CareerData = [
  {
    _id: "6650a1f3e4b0a1c2d3e4f001",
    title: "Senior Frontend Developer",
    department: "Engineering",
    jobType: "Full Time",
    location: "Kathmandu, Nepal",
    experience: "3+ years",
    salaryRange: "Rs. 80,000 – Rs. 120,000 / month",
    description:
      "We're looking for a Senior Frontend Developer to lead the development of fast, accessible, and polished web applications.\n\nYou'll architect reusable component systems, mentor junior developers, and work closely with our design team to ship great user experiences.\n\nResponsibilities:\n- Build and maintain production React / Next.js applications\n- Establish frontend standards, code reviews, and best practices\n- Collaborate with designers and backend engineers on new features\n\nRequirements:\n- Strong experience with React, Next.js, and TypeScript\n- Solid understanding of responsive design and Tailwind CSS\n- Experience with performance optimization and accessibility",
    deadline: "2026-07-31T00:00:00.000Z",
    applicants: 24,
    tags: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    status: "Active",
    createdAt: "2026-06-01T09:30:00.000Z",
    updatedAt: "2026-06-01T09:30:00.000Z",
  },
  {
    _id: "6650a1f3e4b0a1c2d3e4f002",
    title: "Cybersecurity Analyst",
    department: "Security",
    jobType: "Full Time",
    location: "Kathmandu, Nepal",
    experience: "2+ years",
    salaryRange: "Rs. 70,000 – Rs. 110,000 / month",
    description:
      "Join our Security Operations team to defend client infrastructure against evolving threats.\n\nYou'll monitor systems around the clock, investigate incidents, and help harden our clients' security posture.\n\nResponsibilities:\n- Monitor SIEM alerts and triage security events\n- Conduct vulnerability assessments and support penetration tests\n- Lead incident response and document findings\n\nRequirements:\n- Hands-on experience with SOC tooling and SIEM platforms\n- Familiarity with network and application security\n- Relevant certifications (CEH, OSCP, or Security+) are a plus",
    deadline: "2026-07-20T00:00:00.000Z",
    applicants: 11,
    tags: ["SOC", "Penetration Testing", "SIEM", "Incident Response"],
    status: "Active",
    createdAt: "2026-06-03T11:00:00.000Z",
    updatedAt: "2026-06-03T11:00:00.000Z",
  },
  {
    _id: "6650a1f3e4b0a1c2d3e4f003",
    title: "UI/UX Designer",
    department: "Design",
    jobType: "Full Time",
    location: "Lalitpur, Nepal",
    experience: "2–4 years",
    salaryRange: "Rs. 60,000 – Rs. 90,000 / month",
    description:
      "We're seeking a UI/UX Designer who can turn complex problems into clean, intuitive interfaces.\n\nYou'll own the design process end to end — from research and wireframes to polished, production-ready designs.\n\nResponsibilities:\n- Create wireframes, prototypes, and high-fidelity designs in Figma\n- Maintain and extend our design system\n- Partner with engineers to ensure pixel-perfect implementation\n\nRequirements:\n- Strong portfolio demonstrating web and mobile design\n- Proficiency in Figma and modern design workflows\n- Understanding of usability and accessibility principles",
    deadline: "2026-08-15T00:00:00.000Z",
    applicants: 18,
    tags: ["Figma", "Design Systems", "Prototyping", "User Research"],
    status: "Active",
    createdAt: "2026-06-05T08:15:00.000Z",
    updatedAt: "2026-06-05T08:15:00.000Z",
  },
  {
    _id: "6650a1f3e4b0a1c2d3e4f004",
    title: "Backend Developer (Node.js)",
    department: "Engineering",
    jobType: "Remote",
    location: "Remote (Nepal)",
    experience: "2+ years",
    salaryRange: "Rs. 75,000 – Rs. 115,000 / month",
    description:
      "Build the APIs and services that power our products as a Backend Developer on a fully remote team.\n\nYou'll design scalable data models, write reliable services, and keep our systems fast and secure.\n\nResponsibilities:\n- Design and build RESTful APIs with Node.js and Express\n- Model data and optimize queries in MongoDB\n- Write tests and maintain clean, well-documented code\n\nRequirements:\n- Solid experience with Node.js, Express, and MongoDB\n- Understanding of authentication, caching, and API security\n- Comfortable working asynchronously in a remote team",
    deadline: "2026-07-25T00:00:00.000Z",
    applicants: 30,
    tags: ["Node.js", "Express", "MongoDB", "REST API"],
    status: "Active",
    createdAt: "2026-06-04T14:45:00.000Z",
    updatedAt: "2026-06-10T10:00:00.000Z",
  },
  {
    _id: "6650a1f3e4b0a1c2d3e4f005",
    title: "DevOps Engineer",
    department: "Infrastructure",
    jobType: "Full Time",
    location: "Kathmandu, Nepal",
    experience: "3+ years",
    salaryRange: "Rs. 90,000 – Rs. 140,000 / month",
    description:
      "We need a DevOps Engineer to automate our infrastructure and keep deployments smooth and reliable.\n\nYou'll own CI/CD pipelines, containerized workloads, and cloud infrastructure across multiple environments.\n\nResponsibilities:\n- Build and maintain CI/CD pipelines\n- Manage containerized deployments with Docker and Kubernetes\n- Monitor, scale, and secure cloud infrastructure\n\nRequirements:\n- Experience with AWS (or similar cloud providers)\n- Strong knowledge of Docker, Kubernetes, and infrastructure as code\n- Scripting skills and a security-first mindset",
    deadline: "2026-09-05T00:00:00.000Z",
    applicants: 7,
    tags: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    status: "Active",
    createdAt: "2026-06-08T13:20:00.000Z",
    updatedAt: "2026-06-08T13:20:00.000Z",
  },
  {
    _id: "6650a1f3e4b0a1c2d3e4f006",
    title: "Software Instructor / Trainer",
    department: "Education",
    jobType: "Part Time",
    location: "Kathmandu, Nepal",
    experience: "1+ years",
    description:
      "Help shape the next generation of developers as a part-time Software Instructor.\n\nYou'll deliver hands-on training, mentor students, and contribute to our curriculum on modern web development.\n\nResponsibilities:\n- Teach JavaScript and web development fundamentals\n- Mentor students through projects and code reviews\n- Help improve and update course material\n\nRequirements:\n- Practical development experience with JavaScript and the web\n- Strong communication and a passion for teaching\n- Prior mentoring or teaching experience is a plus",
    deadline: "2026-07-10T00:00:00.000Z",
    applicants: 9,
    tags: ["Teaching", "JavaScript", "Mentorship", "Curriculum"],
    status: "Active",
    createdAt: "2026-06-02T16:00:00.000Z",
    updatedAt: "2026-06-02T16:00:00.000Z",
  },
  {
    _id: "6650a1f3e4b0a1c2d3e4f007",
    title: "Frontend Developer Intern",
    department: "Engineering",
    jobType: "Internship",
    location: "Kathmandu, Nepal",
    experience: "Fresher (0–1 years)",
    salaryRange: "Rs. 15,000 – Rs. 20,000 / month (stipend)",
    description:
      "Kickstart your career with a hands-on Frontend Developer internship.\n\nYou'll work alongside our engineering team on real projects, learning modern tools and best practices along the way.\n\nResponsibilities:\n- Assist in building UI components with React\n- Fix bugs and implement small features under guidance\n- Learn version control, code reviews, and team workflows\n\nRequirements:\n- Basic knowledge of HTML, CSS, and JavaScript\n- Familiarity with React is a plus\n- Eagerness to learn and a strong work ethic",
    deadline: "2026-06-05T00:00:00.000Z",
    applicants: 47,
    tags: ["React", "HTML", "CSS", "JavaScript"],
    status: "Closed",
    createdAt: "2026-05-15T10:30:00.000Z",
    updatedAt: "2026-06-06T09:00:00.000Z",
  },
];
